// export const DASHBOARD = "/";
export const LOGIN = "/login";
export const REGISTER = "/register";
export const LOGOUT = "/logout";
export const PROFILE = "/app/me/:username";
export const EDIT_PROFILE = "/app/edit-profile";
export const TASKS = "/app/";
export const COMPLETED = "/app/completed";
export const INCOMPLETED = "/app/incompleted";