// export const DASHBOARD = "/";
export const LOGIN = "/login";
export const REGISTER = "/register";
export const LOGOUT = "/logout";
export const PROFILE = "/me/:username";
export const EDIT_PROFILE = "/edit-profile";
export const TASKS = "/";
export const COMPLETED = "/completed";
export const PENDING = "/pending";